apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-for-argo.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
  selector:
    {{- include "app-for-argo.selectorLabels" . | nindent 4 }}
