replicaCount: 1

image:
  repository: henrsand/app-for-argo
  tag: v20250426212941
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: test.local

service:
  type: LoadBalancer
  port: 80

deployment:
  revisionHistoryLimit: 3

appLabels:
  app: app-for-argo
  version: blue   # <-- for blue-green deployment
